#yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Hacking Life
site_url: https://amandaguglieri.github.io/hackinglife
site_description: My personal knowledge repository
site_author: amandaguglieri

repo_name: amandaguglieri/hackinglife
repo_url: https://github.com/amandaguglieri/hackinglife
edit_uri: blob/main/docs

nav:
    - Home: index.md
    - Cheat sheets:
      - amass: amass.md
      - apktool: apktool.md
      - arjun: arjun.md
      - arspoof- dniff: arpspoof-dniff.md
      - backdoors: data-transfer-and-backdoors.md
      - bash: bash.md
      - beef: beef.md
      - burpsuite: burpsuite.md
      - cewl: cewl.md
      - cff explorer: cff-explorer.md
      - cupp: cupp-common-user-password-profiler.md
      - cyber acronyms: acronyms.md
      - crt.sh: ctr.md
      - crunch: crunch.md
      - dirb: dirb.md
      - dnscan: dnscan.md
      - dnspy: dnspy.md
      - dotpeek: dotpeek.md 
      - drozer: drozer.md
      - echo mirage: echo-mirage.md
      - emacs: emacs.md
      - enum: enum.md
      - enum4linux: enum4linux.md
      - exiftool: [exiftool.md]
      - feroxbuster: feroxbuster.md
      - fping: fping.md
      - frida: frida.md
      - ffuzz: ffuzz.md
      - git: git.md
      - gobuster: gobuster.md
      - google dorks: google-dorks.md
      - grep: grep.md
      - hashcat: hashcat.md
      - httprint: httprint.md
      - hydra: hydra.md
      - hugo: hugo.md
      - i3: i3.md
      - impacket: impacket.md
      - john the ripper: john-the-ripper.md
      - jwt-tool: jwt-tool.md
      - kiterunner: kiterunner.md
      - knockpy: knockpy.md
      - markdown: markdown.md
      - mariadb: mariadb.md
      - masscan: masscan.md
      - metasploit: metasploit.md
      - mitm_relay: mitm-relay.md
      - mobsf: mobsf.md
      - moodlescan: moodlescan.md
      - msfvenom: msfvenom.md
      - msSQL: mssql.md
      - mySQL: mysql.md
      - nessus: nessus.md
      - netcat: netcat.md
      - netdiscover: netdiscover.md
      - nikto: nikto.md
      - nmap: nmap.md
      - objection: objection.md
      - openSSL: openssl.md
      - ophcrack: ophcrack.md
      - owasp-zap: owasp-zap.md 
      - p0f: p0f.md
      - PeSecurity: pesecurity.md
      - ping: ping.md
      - powershell: powershell.md
      - process hacker tool 2: process-hacker-tool.md
      - regshot: regshot.md
      - samba suite: samba-suite.md
      - samrdump: samrdump.md
      - sql injection (manual): sqli-manual-attack.md
      - sqlmap: sqlmap.md
      - ssh tunneling: ssh-tunneling.md
      - sys internals suite: sys-internals-suite.md
      - sublist3r: sublist3r.md
      - tcpdump: tcpdump.md
      - veil: veil.md
      - vim: vim.md
      - w3af: w3af.md
      - weevely: weevely.md
      - wfuzz: wfuzz.md
      - Window Detective: window-detective.md
      - winfo: winfo.md
      - winPEAS: winpeas.md
      - winspy: winspy.md
      - wpscan: wpscan.md
      - xsser: xsser.md
    - Courses:
      - Burpsuite:
          - Index of labs: burpsuite/burpsuite-labs.md
          - SQLi labs: burpsuite/burpsuite-sqli.md
          - XSS labs: burpsuite/burpsuite-xss.md
      - eJPT: ejpt.md
      - Hacking APIs: 
          - Intro: hackingapis/index.md
          - Setting up the environmet: hackingapis/setting-up-kali.md
          - Api Reconnaissance: hackingapis/api-reconnaissance.md
          - Endpoint Analysis: hackingapis/endpoint-analysis.md
          - Scanning APIs: hackingapis/scanning-apis.md
          - API authentication attacks: hackingapis/api-authentication-attacks.md
          - Exploiting API Authorization: hackingapis/exploiting-api-authorization.md
          - Testing improper assets management: hackingapis/improper-assets-management.md
          - Mass assignment: hackingapis/mass-assignment.md
          - Server-side Request Forgery: hackingapis/server-side-request-forgery-ssrf.md
          - Injections attacks: hackingapis/injection-attacks.md
          - Evasion and combining techniques: hackingapis/evasion-combining-techniques.md
          - Setting up the labs + writeups: hackingapis/other-labs.md
    - Walkthroughs:
      - Vulnhub GoldenEye 1: vulnhub-goldeneye-1.md
      - Vulnhub Raven 1: vulnhub-raven-1.md
      - Vulnhub Raven 2: vulnhub-raven-2.md
      - HTB metatwo: htb-metatwo.md
      - HTB photobomb: htb-photobomb.md
      - HTB support: htb-support.md
      - HTB trick: htb-trick.md
    - Beginners' guide:
      - checksum: checksum.md
      - dictionaries: dictionaries.md
      - HTTP Authentication schemes: http-authentication-schemes.md 
      - HTTP headers: http-headers.md
      - My mkdocs and material customized setup: my-mkdocs-material-customization.md
      - NetBIOS: netbios.md      
      - Network traffic capture: network-traffic-capture.md
      - pdm: pdm.md
      - operating systems: operating-systems.md
      - proxies: proxies.md
      - python: python.md
      - Reverse shells: reverse-shells.md
      - Spawn a shell: spawn-a-shell.md
      - ssh for github: ssh-for-github.md
      - VirtualBox: virtualbox.md
    - Network Services Pentestings:
        - 21 ftp: 21-ftp.md
        - 23 telnet: 23-telnet.md
        - 445 smb: 445-smb.md
        - 873 rsync: 873-rsync.md
        - 1433 mssql: 1433-mssql.md
        - 3306 mariadb: 3306-mariadb-mysql.md
        - 3389 RDP: 3389-rdp.md
        - 5432 postgresql: 5432-postgresql.md
        - 6379 redis: 6379-redis.md
        - 27017 mongodb: 27017-27018-mongodb.md
        - 27018 mongodb: 27017-27018-mongodb.md
        - 55007 dovecot: 55007-55008-dovecot.md
        - 55008 dovecot: 55007-55008-dovecot.md
    - Pentesting web:
        - Tools and attacks: index-attacks-tools-web-pentesting.md
        - Buffer overflow attack: buffer-overflow.md
        - Captcha Replay Attack: captcha-replay-attack.md
        - CRLF attack- Carriage Return and Linefeed attack: carriage-return-and-linefeed-crlf.md 
        - CSRF attack- Cross-Site Request Forgery: cross-site-request-forgery-csrf.md
        - Directory traversal attack: directory-traversal.md
        - File upload: file-upload.md
        - LFI attack- Local File Inclusion attack: local-file-inclusion-lfi.md
        - RCE attack- Remote Code Execution attack: remote-code-execution-rce.md
        - RFD attack- Reflected File Download attack: reflected-file-download-rfd.md
        - RFI attack- Remote File Inclusion attack: remote-file-inclusion-rfi.md
        - Session puzzling attack: session-puzzling-or-session-variable-overloading.md
        - SSRF attack- Server Side Request Forgery attack: server-side-request-forgery-ssrf.md
        - SQL injection attack: sql-injection.md
        - XFS attack- Cross-frame Scripting attack: cross-frame-scripting-xfs.md
        - XSS attack- Cross-site Scripting attack: cross-site-scripting-xss.md
    - Pentesting mobile: 
        - Setting up the mobile pentesting environment: setting-up-mobile-penstesting.md
    - Pentesting Thick applications: 
        - Tools for pentesting thick clients applications: thick-applications/tools-for-thick-apps.md
        - Introduction: thick-applications/tca-introduction.md
        - Basic lab setup: thick-applications/tca-basic-lab-setup.md
        - First challenge- Enabling a button: thick-applications/tca-first-challenge.md
        - Information gathering phase: thick-applications/tca-information-gathering-phase.md
        - Traffic analysis: thick-applications/tca-traffic-analysis.md
        - Attacking thick clients applications: thick-applications/tca-attacking-thick-clients-applications.md
        - Reversing and patching thick clients applications: thick-applications/tca-reversing-and-patching.md
        - Common vulnerabilities: thick-applications/tca-common-vulnerabilities.md
        - Checklist when pentesting Thick applications: thick-applications/thick-application-checklist.md
    - Pentesting Cloud: pentesting-cloud.md
    - Linux:
        - Privilege Escalation:
          - Index: index-linux-privilege-escalation.md
          - Dirty cow: dirty-cow.md
          - Suid binaries: suid-binaries.md
          - Tools:
            - Enumerate with Linux Privilege Checker: linux-privilege-checker.md
            - Linux Exploit Suggester: linux-exploit-suggester.md
    - Windows: 
        - Attacks:
          - ARP Poisoning: arp-poisoning.md
          - Null session attack: windows-null-session-attack.md
        - Privilege Escalation: index-windows-privilege-escalation.md
        - Persistence:
          - Create a Registry: create-a-registry.md
    - Lateral movements: lateral-movements.md
    - Cryptography: cryptography.md 
    - Forensic: computer-forensic-fundamentals.md
    - Wireless security: wireless-security.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  icon:
    logo: material/alpha-h-box
    admonition: 
      <type>: material/alert-box-outline
  favicon: img/favicon.png

  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: pink
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
    - search
    - tags:
        tags_file: tags.md
        
    #- mkpdfs:
      # company: HackingLife
      #  author: amandaguglieri
      #  toc_title: ToC
      #  design: design/style.css

      #- pdf-export

extra_css:
    - css/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

    
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true 

