#yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Hacking Life
site_url: https://amandaguglieri.github.io/hackinglife
site_description: My personal knowledge repository
site_author: amandaguglieri

repo_name: amandaguglieri/hackinglife
repo_url: https://github.com/amandaguglieri/hackinglife
edit_uri: blob/main/docs

nav:
    - Home: index.md
    - Cheat sheets:
      - amass: amass.md
      - apktool: apktool.md
      - bash: bash.md
      - cewl: cewl.md
      - cupp: common-user-password-profiler-cupp.md
      - cyber acronyms: acronyms.md
      - crt.sh: ctr.md
      - crunch: crunch.md
      - dirb: dirb.md
      - dnscan: dnscan.md
      - drozer: drozer.md
      - emacs: emacs.md
      - feroxbuster: feroxbuster.md
      - fping: fping.md
      - frida: frida.md
      - git: git.md
      - google dorks: google-dorks.md
      - hashcat: hashcat.md
      - httprint: httprint.md
      - hydra: hydra.md
      - hugo: hugo.md
      - i3: i3.md
      - impacket: impacket.md
      - john the ripper: john-the-ripper.md
      - markdown: markdown.md
      - mariadb: mariadb.md
      - masscan: masscan.md
      - mobsf: mobsf.md
      - msSQL: mssql.md
      - mySQL: mysql.md
      - nessus: nessus.md
      - netcat: netcat.md
      - netdiscover: netdiscover.md
      - nmap: nmap.md
      - objection: objection.md
      - openSSL: openssl.md
      - ophcrack: ophcrack.md
      - p0f: p0f.md
      - ping: ping.md
      - powershell: powershell.md
      - sql injection (manual): sqli-manual-attack.md
      - sqlmap: sqlmap.md
      - ssh tunneling: ssh-tunneling.md
      - sublist3r: sublist3r.md
      - vim: vim.md
      - winPEAS: winpeas.md
      - wpscan: wpscan.md
      - xsser: xsser.md
    - Courses:
      - Hacking APIs: 
          - Intro: hackingapis/index.md
          - Api Reconnaissance: hackingapis/apireconnaissance.md
          - Endpoint Analysis: hackingapis/endpoint-analysis.md
          - Scanning APIs: hackingapis/scanning-apis.md
          - API authentication attacks: hackingapis/api-authentication-attacks.md
          - Exploiting API Authorization: hackingapis/exploiting-api-authorization.md
          - Improper assets management: hackingapis/improper-assets-management.md
          - Mass assignment: hackingapis/mass-assignment.md
          - Server-side Request Forgery: hackingapis/server-side-request-forgery.md
          - Injections attacks: hackingapis/injection-attacks.md
          - Evasion and combining techniques: hackingapis/evasion-combining-techniques.md
          - Labs: hackingapis/other-labs.md
      - eJPT: ejpt.md
    - Walkthroughs:
      - Vulnhub GoldenEye1: vulnhub-goldeneye-1.md
      - HTB metatwo: htb-metatwo.md
      - HTB photobomb: htb-photobomb.md
      - HTB support: htb-support.md
      - HTB trick: htb-trick.md
    - Beginners' guide:
      - checksum: checksum.md
      - dictionaries: dictionaries.md
      - HTTP Authentication schemes: http-authentication-schemes.md 
      - Network traffic capture: network-traffic-capture.md
      - pdm: pdm.md
      - python: python.md
      - Reverse shells: reverse-shells.md
      - ssh for github: ssh-for-github.md
    - Network Services Pentestings:
        - 21 ftp: 21-ftp.md
        - 23 telnet: 23-telnet.md
        - 445 smb: 445-smb.md
        - 873 rsync: 873-rsync.md
        - 1433 mssql: 1433-mssql.md
        - 3306 mariadb: 3306-mariadb-mysql.md
        - 3389 RDP: 3389-rdp.md
        - 5432 postgresql: 5432-postgresql.md
        - 6379 redis: 6379-redis.md
        - 27017 mongodb: 27017-27018-mongodb.md
        - 27018 mongodb: 27017-27018-mongodb.md
        - 55007 dovecod: 55007-55008-dovecot.md
        - 55008 dovecod: 55007-55008-dovecot.md
    - Pentesting web:
        - Tools and attacks: index-attacks-tools-web-pentesting.md
        - Buffer overflow attack: buffer-overflow.md
        - CRLF attack- Carriage Return and Linefeed attack: carriage-return-and-linefeed-crlf.md 
        - CSRF attack- Cross-Site Request Forgery: cross-site-request-forgery-csrf.md
        - Directory traversal attack: directory-traversal.md
        - LFI attack- Local File Inclusion attack: local-file-inclusion-lfi.md
        - RCE attack- Remote Code Execution attack: remote-code-execution-rce.md
        - RFD attack- Reflected File Download attack: reflected-file-download-rfd.md
        - RFI attack- Remote File Inclusion attack: remote-file-inclusion-rfi.md
        - Session puzzling attack: session-puzzling-or-session-variable-overloading.md
        - SSRF attack- Server Side Request Forgery attack: server-side-request-forgery-ssrf.md
        - SQL injection attack: sql-injection.md
        - XFS attack- Cross-frame Scripting attack: cross-frame-scripting-xfs.md
        - XSS attack- Cross-site Scripting attack: cross-site-scripting-xss.md
    - Pentesting mobile: 
        - Setting up the mobile pentesting environment: setting-up-mobile-penstesting.md
    - To-do list: todolist.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  icon:
    logo: material/alpha-h-box
  favicon: img/favicon.png


  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode


    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: pink
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

