#yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Hacking Life
site_url: https://amandaguglieri.github.io/hackinglife
site_description: My personal knowledge repository
site_author: amandaguglieri
repo_name: amandaguglieri/hackinglife
repo_url: https://github.com/amandaguglieri/hackinglife
nav:
    - Home: index.md
    - cheat sheets:
      - amass: amass.md
      - bash: bash.md
      - cyber acronyms: acronyms.md
      - git: git.md
      - hugo: hugo.md
      - i3: i3.md
      - markdown: markdown.md
      - nmap: nmap.md
      - powershell: powershell.md
      - sql injection: sqli.md
      - sqlmap: sqlmap.md
      - ssh tunneling: ssh-tunneling.md
      - vim: vim.md
    - courses:
      - Hacking APIs: 
          - Intro: hackingapis/index.md
          - Api Reconnaissance: hackingapis/apireconnaissance.md
          - Endpoint Analysis: hackingapis/endpoint-analysis.md
          - Scanning APIs: hackingapis/scanning-apis.md
          - API authentication attacks: hackingapis/api-authentication-attacks.md
          - Exploiting API Authorization: hackingapis/exploiting-api-authorization.md
          - Improper assets management: hackingapis/improper-assets-management.md
          - Mass assignment: hackingapis/mass-assignment.md
          - Server-side Request Forgery: hackingapis/server-side-request-forgery.md
          - Injections attacks: hackingapis/injection-attacks.md
          - Evasion and combining techniques: hackingapis/evasion-combining-techniques.md
          - Labs: hackingapis/other-labs.md
    - walkthroughs:
      - metatwo: htb-metatwo.md
      - photobomb: htb-photobomb.md
      - support: htb-support.md
      - trick: htb-trick.md
    - Beginners' guide:
      - checksum: checksum.md
      - documentation: documentation.md
      - ssh for github: ssh-for-github.md
    - Pentesting web:
      - sql injection: sql-injection.md
    - Network Services Pentestings:
        - 21 ftp: 21-ftp.md
        - 23 telnet: 23-telnet.md
        - 445 smb: 445-smb.md
        - 873 rsync: 873-rsync.md
        - 3306 mariadb: 3306-mariadb-mysql.md
        - 3389 RDP: 3389-rdp.md
        - 5432 postgresql: 5432-postgresql.md
        - 6379 redis: 6379-redis.md
        - 27017 mongodb: 27017-27018-mongodb.md
        - 27018 mongodb: 27017-27018-mongodb.md
    - To-do list: todolist.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight

  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode


    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: pink
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
