#yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Hacking Life
site_url: https://amandaguglieri.github.io/hackinglife
site_description: My personal knowledge repository
site_author: amandaguglieri
repo_name: amandaguglieri/hackinglife
repo_url: https://github.com/amandaguglieri/hackinglife
edit_uri: blob/main/docs
nav:
    - Home: index.md
    - Cheat sheets:
      - amass: amass.md
      - apktool: apktool.md
      - bash: bash.md
      - cyber acronyms: acronyms.md
      - crt.sh: ctr.md
      - dnscan: dnscan.md
      - drozer: drozer.md
      - fping: fping.md
      - frida: frida.md
      - git: git.md
      - google dorks: google-dorks.md
      - hugo: hugo.md
      - i3: i3.md
      - impacket: impacket.md
      - markdown: markdown.md
      - mariadb: mariadb.md
      - masscan: masscan.md
      - mobsf: mobsf.md
      - msSQL: mssql.md
      - mySQL: mysql.md
      - nessus: nessus.md
      - netcat: netcat.md
      - nmap: nmap.md
      - objection: objection.md
      - openSSL: openssl.md
      - p0f: p0f.md
      - ping: ping.md
      - powershell: powershell.md
      - sql injection: sqli.md
      - sqlmap: sqlmap.md
      - ssh tunneling: ssh-tunneling.md
      - sublist3r: sublist3r.md
      - vim: vim.md
      - winPEAS: winpeas.md
    - Courses:
      - Hacking APIs: 
          - Intro: hackingapis/index.md
          - Api Reconnaissance: hackingapis/apireconnaissance.md
          - Endpoint Analysis: hackingapis/endpoint-analysis.md
          - Scanning APIs: hackingapis/scanning-apis.md
          - API authentication attacks: hackingapis/api-authentication-attacks.md
          - Exploiting API Authorization: hackingapis/exploiting-api-authorization.md
          - Improper assets management: hackingapis/improper-assets-management.md
          - Mass assignment: hackingapis/mass-assignment.md
          - Server-side Request Forgery: hackingapis/server-side-request-forgery.md
          - Injections attacks: hackingapis/injection-attacks.md
          - Evasion and combining techniques: hackingapis/evasion-combining-techniques.md
          - Labs: hackingapis/other-labs.md
      - eJPT: ejpt.md
    - Walkthroughs:
      - metatwo: htb-metatwo.md
      - photobomb: htb-photobomb.md
      - support: htb-support.md
      - trick: htb-trick.md
    - Beginners' guide:
      - checksum: checksum.md
      - pdm: pdm.md
      - python: python.md
      - ssh for github: ssh-for-github.md
    - Pentesting web:
      - Reverse shells: reverse-shells.md
      - sql injection: sql-injection.md
    - Network Services Pentestings:
        - 21 ftp: 21-ftp.md
        - 23 telnet: 23-telnet.md
        - 445 smb: 445-smb.md
        - 873 rsync: 873-rsync.md
        - 1433 mssql: 1433-mssql.md
        - 3306 mariadb: 3306-mariadb-mysql.md
        - 3389 RDP: 3389-rdp.md
        - 5432 postgresql: 5432-postgresql.md
        - 6379 redis: 6379-redis.md
        - 27017 mongodb: 27017-27018-mongodb.md
        - 27018 mongodb: 27017-27018-mongodb.md
    - Pentesting mobile: 
        - Setting up the mobile pentesting environment: setting-up-mobile-penstesting.md
    - To-do list: todolist.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  icon:
    logo: material/alpha-h-box
  favicon: img/favicon.png


  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode


    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: pink
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
